env_config: "Environment/EnvConfig.yaml"
agent_config: "Agents/A2CConfig.yaml"

max_step: 400
replay_buffer_size: 10000
batch_size: 64
updates_per_episode: 50
target_model_update_freq: 500
moving_average_window_size: 50
save_interval: 500
log_interval: 50